CREATE
OR REPLACE DATABASE SYNTHEA;

CREATE
OR REPLACE SCHEMA SYNTHEA;

CREATE
OR REPLACE TABLE SYNTHEA.SYNTHEA.ALLERGIES as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.ALLERGIES;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.CARE_PLANS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.CARE_PLANS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.CLAIMS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.CLAIMS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.CLAIMS_TX as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.CLAIMS_TX;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.CONDITIONS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.CONDITIONS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.DEVICES as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.DEVICES;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.ENCOUNTERS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.ENCOUNTERS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.IMAGING_STUDIES as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.IMAGING_STUDIES;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.IMMUNIZATIONS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.IMMUNIZATIONS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.MEDICATIONS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.MEDICATIONS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.OBSERVATIONS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.OBSERVATIONS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.ORGANIZATIONS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.ORGANIZATIONS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.PATIENTS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.PATIENTS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.PAYERS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.PAYERS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.PAYER_TRANSITIONS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.PAYER_TRANSITIONS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.PROCEDURES as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.PROCEDURES;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.PROVIDERS as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.PROVIDERS;
CREATE
    OR REPLACE TABLE SYNTHEA.SYNTHEA.SUPPLIES as
select
    *
from
    SYNTHETIC_HEALTH_CARE_DATA.SILVER.SUPPLIES;
select
    a.claim_id,
    b.payer_id
from
    claims a
    join payers b on a.secondary_patient_insurance_id = b.payer_id;